CREATE TABLE EMPLOYEE (
EMPLOYEEID INTEGER NOT NULL, 
EMPLOYEENAME VARCHAR(255), 
AddressId INTEGER, 
PRIMARY KEY (EMPLOYEEID)
)

CREATE TABLE ADDRESS (
ADDRESSID INTEGER NOT NULL, 
ADDRESSCITY VARCHAR(255), 
ADDRESSCOUNTRY VARCHAR(255), 
PRIMARY KEY (ADDRESSID)
)

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_AddressId FOREIGN KEY (AddressId) REFERENCES ADDRESS (ADDRESSID)
